version: '3.8'

services:
  # Django Application
  web:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/app
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --workers 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/api/health/"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 40s
