# Generated by Django 4.2.25 on 2025-10-02 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique conversation ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Conversation title (auto-generated from first message)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        default="general",
                        help_text="Type of agent handling this conversation (general, support, invoice)",
                        max_length=50,
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        default="gemini",
                        help_text="LLM provider used for this conversation",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the conversation",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this conversation is active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Creation timestamp"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update timestamp"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this conversation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "agent_conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique message ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("agent", "Agent"), ("system", "System")],
                        help_text="Role of the message sender",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "agent_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of agent that generated this message (if role=agent)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (context, tokens used, etc.)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Creation timestamp"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agents.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who sent this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "agent_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"], name="agent_messa_convers_7ad657_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["workspace", "user", "-updated_at"], name="agent_conve_workspa_d155f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["workspace", "-updated_at"], name="agent_conve_workspa_c3271a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="agent_conve_user_id_230a21_idx"
            ),
        ),
    ]
