# Generated by Django 4.2.25 on 2025-10-01 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, help_text="Unique ID", primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Workspace name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Optional description", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Creation timestamp")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Last update timestamp")),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "db_table": "workspaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMember",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, help_text="Unique member ID", primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")], default="member", help_text="Role of the user", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Creation timestamp")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Last update timestamp")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Member",
                "verbose_name_plural": "Workspace Members",
                "db_table": "workspace_members",
                "ordering": ["role", "updated_at"],
                "unique_together": {("user", "workspace")},
            },
        ),
    ]
